version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker:/var/lib/mysql
      - ./checkapp_schema.sql:/docker-entrypoint-initdb.d/checkapp_schema.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  go_app:
    build: .
    env_file:
      - .env
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
