@local_hostname = http://localhost:8083/api/v1/
@remote_hostname = https://api.asiendosoftware.xyz/api/v1/

@host = {{local_hostname}}
# @host = {{remote_hostname}}
GET {{host}}

###
GET {{host}}users

###
GET {{host}}users/2
###

GET {{host}}companies

###
GET {{host}}qrs

###
GET {{host}}qrs/1

###
POST {{host}}users

# {
#     "name": "shimeji",
#     "company_id": 1,
#     "rut": "55",
#     "role": "based",
#     "email": "smj@sml.com",
#     "password": "tomandoleche123"
# }
{
    "name": "cr7",
    "company_id": 2,
    "rut": "7",
    "role": "siu",
    "email": "elbichooo",
    "password": "messilover"
}
###
POST {{host}}login
content-type: application/json

{
    "email": "smj@sml.com",
    "password": "tomandoleche123"
}
###

POST {{host}}login
content-type: application/json

{
    "email": "mjm@sml.com",
    "password": "bruh"
}
###
GET {{host}}logout

###
GET {{host}}private/attendance/today

###
###
GET {{host}}private/me

###
GET {{host}}private/companies/generate/2

###
GET {{host}}private/qrs/image/1

###
# POST {{host}}private/attendance

GET {{host}}logout

### 


### 
    // "location": "-39.833392642198596, -73.24520728771456" // el 10k

    # "location": "-40.07086281924284, -72.8730258237025",

POST {{host}}private/attendance/
content-type: application/json

{
    "company_id": 1,
    "location": "-39.833392642198596, -73.24520728771456",
    "device_secret_key": "asdfb",
    "event_type": "AUTO"
}
###
GET {{host}}private/attendance/last


###
GET {{host}}reset/attendance/today
###

###
GET {{host}}reset/attendance/all
###
POST {{host}}private/attendance
content-type: application/json

{
    "company_id": 1,
    "user_id": 2,
    "location": "-30.0, -70.2"
}

###

GET {{host}}private/attendance