@local_hostname = http://localhost:8083/api/v1/
@remote_hostname = https://api.asiendosoftware.xyz/api/v1/

# @host = {{local_hostname}}
@host = {{remote_hostname}}

# POST {{host}}private/users
# content-type: application/json

# {
#     "name": "kaos",
#     "company_id": 1,
#     "rut": "37",
#     "role": "cringe",
#     "email": "kaos@kaos.com",
#     "password": "kaos"
# }

# {
#     "name": "cr7",
#     "company_id": 2,
#     "rut": "7",
#     "role": "cringe",
#     "email": "bicho@cr7.com",
#     "password": "messi"
# }

# {
#     "name": "shimeji",
#     "company_id": 1,
#     "rut": "55",
#     "role": "based",
#     "email": "smj@sml.com",
#     "password": "tomandoleche123"
# }
###
POST {{host}}login
content-type: application/json

{
    "email": "smj@sml.com",
    "password": "tomandoleche123"
}
###

POST {{host}}login
content-type: application/json

{
    "email": "mjm@sml.com",
    "password": "bruh"
}
###
POST {{host}}login
content-type: application/json

{
    "email": "kaos@kaos.com",
    "password": "kaos"
}
###
POST {{host}}login
content-type: application/json

{
    "email": "cristo@heaven.com",
    "password": "cristo"
}
###
PUT {{host}}private/users/image
content-type: application/json

{
    "url": "https://64.media.tumblr.com/dcb8c0b4b1d8e71e46cd87c51b2a2806/623c62256a38dbac-05/s640x960/91b6ac2904ab60325c9360496072df51107f8cdb.jpg"
}
###

GET {{host}}logout
######
GET {{host}}private/attendance/today
###

GET {{host}}private/attendance/tomorrow
###
GET {{host}}private/attendance/company/monthly
###

GET {{host}}private/attendance/me
###
GET {{host}}private/me

###
GET {{host}}private/companies/generate/2
###

###
GET {{host}}private/companies/attendance
###


GET {{host}}private/qrs/image/1

###
# POST {{host}}private/attendance

GET {{host}}logout

### 


### 
    // "location": "-39.833392642198596, -73.24520728771456" // el 10k

    # "location": "-40.07086281924284, -72.8730258237025",

POST {{host}}private/attendance/
content-type: application/json

{
    "company_id": 1,
    "location": "-39.833392642198596, -73.24520728771456",
    "device_secret_key": "asdfb",
    "event_type": "CHECK_OUT"
}
###
GET {{host}}private/attendance/last
###

GET {{host}}reset/attendance/today
###

POST {{host}}private/attendance
content-type: application/json

{
    "company_id": 1,
    "user_id": 2,
    "location": "-30.0, -70.2"
}

###

GET {{host}}private/attendance